apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobsf
  namespace: mobsf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobsf
  template:
    metadata:
      labels:
        app: mobsf
    spec:
      containers:
        - name: mobsf
          image: opensecurity/mobile-security-framework-mobsf:v3.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: mobsf-storage
              mountPath: /app/data
      volumes:
        - name: mobsf-storage
          persistentVolumeClaim:
            claimName: mobsf-pvc
