apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobsf-pvc
  namespace: mobsf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: mobsf-pv  # 👈 Прямая привязка к конкретному PV
