apiVersion: v1
kind: PersistentVolume
metadata:
  name: mobsf-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /disks
  claimRef:
    name: mobsf-pvc            # 👈 Обратная привязка
    namespace: mobsf
    kind: PersistentVolumeClaim
    apiVersion: v1
